server:
  port: 9090

info:
  app:
    name: CRM
    description: learning spring
    version: 1.0.0

management:
  endpoints:
    web:
      exposure:
        include: "*"

keycloak:
  auth-server-url: http://love-u2.ru:8180/auth/
  realm: new
  resource: app
  public-client: true
  ssl-required: none
