server:
  port: 9090

spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/web_customer_tracker?useSSL=false&serverTimezone=UTC
    username: springstudent
    password: springstudent

